signage:
  ros__parameters:
    signage_stand_alone: true
    ignore_emergency_stoppped: false
    ignore_manual_driving: false
    set_goal_by_distance: false
    goal_distance: 1.0 # meter
    check_fms_time: 5.0 # second
    emergency_ignore_period: 5.0 # second
    emergency_repeat_period: 180.0 # second
    accept_start: 5.0 # second
    monitor_width: 1920
    monitor_height: 540
    announce:
      emergency: true
      restart_engage: true
      door_close: true
      door_open: true
      engage: true
      thank_you: true
      in_emergency: true
      going_to_depart: true
      going_to_arrive: true
