signage:
  ros__parameters:
    signage_stand_alone: true
    ignore_emergency_stopped: true
    ignore_disconnected: false
    ignore_manual_driving: false
    set_goal_by_distance: false
    freeze_emergency: true
    goal_distance: 1.0 # meter
    check_fms_time: 2.0 # second
    emergency_ignore_period: 5.0 # second
    emergency_repeat_period: 180.0 # second
    accept_start: 5.0 # second
    override_status_bus_stop: true
    force_local_display: true
    monitor_width: 1920
    monitor_height: 360
    announce:
      emergency: false
      restart_engage: false
      door_close: false
      door_open: false
      engage: false
      thank_you: false
      in_emergency: false
      going_to_depart: false
      going_to_arrive: false
