name: Check spelling (all files)

on:
  workflow_dispatch:
    inputs:
      ignore_patterns:
        description: "ignore patterns (ex. *.svg|*.osm)"
        required: false

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare node
        uses: actions/setup-node@v2

      - name: Install cspell
        run: |
          npm install cspell

      - name: Install spell check dictionary
        run: npm install --ignore-scripts https://github.com/tier4/autoware-spell-check-dict

      - name: Check spelling
        run: |
          # The cspell-action might not be able to exclude specific files.
          # So use cspell package directly instead.
          # How to exclude specific files:
          #   Ex. "**/!(*.osm|*.svg|CHANGELOG.rst)"
          ./node_modules/.bin/cspell \
            --config node_modules/@tier4/autoware-spell-check-dict/.cspell.json \
            "**/!(CHANGELOG.rst|package.xml|${{ github.event.inputs.ignore_patterns }})" \
            2> /dev/null
