name: Check spelling

on:
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install spell check dictionary
        run: npm install --ignore-scripts https://github.com/tier4/autoware-spell-check-dict

      - name: Add project-specific cspell overrides
        run: |
          jq '.words += ["testpaths", "pythonpath", "addopts"]' node_modules/@tier4/autoware-spell-check-dict/.cspell.json > /tmp/cspell.json \
            && mv /tmp/cspell.json node_modules/@tier4/autoware-spell-check-dict/.cspell.json

      - uses: streetsidesoftware/cspell-action@v1.3.2
        with:
          config: "node_modules/@tier4/autoware-spell-check-dict/.cspell.json"
